#!/bin/python3
from artificial_intelligence import *
from color import *
from parser import *
from connection import *


if __name__ == "__main__":
    try:
        parser = Parser(sys.argv[1:])
        print(f"Hostname: {parser.get_hostname()}")
        print(f"Port: {parser.get_port()}")
        print(f"Team name: {parser.get_name()}")
        my_ai = Ai(sys.argv[0], parser.get_hostname(), parser.get_port(), parser.get_name(), parser.get_child())
        Connection(my_ai).poll()
    except SuccessException:
        sys.exit(0)
    except CriticalException as e:
        print(f"{RED}Error: {e}{RESET}", file=sys.stderr)
        sys.exit(84)
    except KeyboardInterrupt:
        print(f"{RED}Stopping with CTRL+C{RESET}")
    #except Exception as e:
    #    print(f"{RED}Unexpected error: {e}{RESET}", file=sys.stderr)
    #    sys.exit(84)
